# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/renan/windowManager/rwm-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/renan/windowManager/rwm-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renan/windowManager/rwm-project/CMakeFiles /home/renan/windowManager/rwm-project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renan/windowManager/rwm-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rwm

# Build rule for target.
rwm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rwm
.PHONY : rwm

# fast build rule for target.
rwm/fast:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/build
.PHONY : rwm/fast

inc/moc_about.o: inc/moc_about.cxx.o
.PHONY : inc/moc_about.o

# target to build an object file
inc/moc_about.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_about.cxx.o
.PHONY : inc/moc_about.cxx.o

inc/moc_about.i: inc/moc_about.cxx.i
.PHONY : inc/moc_about.i

# target to preprocess a source file
inc/moc_about.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_about.cxx.i
.PHONY : inc/moc_about.cxx.i

inc/moc_about.s: inc/moc_about.cxx.s
.PHONY : inc/moc_about.s

# target to generate assembly for a file
inc/moc_about.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_about.cxx.s
.PHONY : inc/moc_about.cxx.s

inc/moc_border.o: inc/moc_border.cxx.o
.PHONY : inc/moc_border.o

# target to build an object file
inc/moc_border.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_border.cxx.o
.PHONY : inc/moc_border.cxx.o

inc/moc_border.i: inc/moc_border.cxx.i
.PHONY : inc/moc_border.i

# target to preprocess a source file
inc/moc_border.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_border.cxx.i
.PHONY : inc/moc_border.cxx.i

inc/moc_border.s: inc/moc_border.cxx.s
.PHONY : inc/moc_border.s

# target to generate assembly for a file
inc/moc_border.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_border.cxx.s
.PHONY : inc/moc_border.cxx.s

inc/moc_colordialog.o: inc/moc_colordialog.cxx.o
.PHONY : inc/moc_colordialog.o

# target to build an object file
inc/moc_colordialog.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_colordialog.cxx.o
.PHONY : inc/moc_colordialog.cxx.o

inc/moc_colordialog.i: inc/moc_colordialog.cxx.i
.PHONY : inc/moc_colordialog.i

# target to preprocess a source file
inc/moc_colordialog.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_colordialog.cxx.i
.PHONY : inc/moc_colordialog.cxx.i

inc/moc_colordialog.s: inc/moc_colordialog.cxx.s
.PHONY : inc/moc_colordialog.s

# target to generate assembly for a file
inc/moc_colordialog.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_colordialog.cxx.s
.PHONY : inc/moc_colordialog.cxx.s

inc/moc_colorsel.o: inc/moc_colorsel.cxx.o
.PHONY : inc/moc_colorsel.o

# target to build an object file
inc/moc_colorsel.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_colorsel.cxx.o
.PHONY : inc/moc_colorsel.cxx.o

inc/moc_colorsel.i: inc/moc_colorsel.cxx.i
.PHONY : inc/moc_colorsel.i

# target to preprocess a source file
inc/moc_colorsel.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_colorsel.cxx.i
.PHONY : inc/moc_colorsel.cxx.i

inc/moc_colorsel.s: inc/moc_colorsel.cxx.s
.PHONY : inc/moc_colorsel.s

# target to generate assembly for a file
inc/moc_colorsel.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_colorsel.cxx.s
.PHONY : inc/moc_colorsel.cxx.s

inc/moc_dateclock.o: inc/moc_dateclock.cxx.o
.PHONY : inc/moc_dateclock.o

# target to build an object file
inc/moc_dateclock.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dateclock.cxx.o
.PHONY : inc/moc_dateclock.cxx.o

inc/moc_dateclock.i: inc/moc_dateclock.cxx.i
.PHONY : inc/moc_dateclock.i

# target to preprocess a source file
inc/moc_dateclock.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dateclock.cxx.i
.PHONY : inc/moc_dateclock.cxx.i

inc/moc_dateclock.s: inc/moc_dateclock.cxx.s
.PHONY : inc/moc_dateclock.s

# target to generate assembly for a file
inc/moc_dateclock.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dateclock.cxx.s
.PHONY : inc/moc_dateclock.cxx.s

inc/moc_defs.o: inc/moc_defs.cxx.o
.PHONY : inc/moc_defs.o

# target to build an object file
inc/moc_defs.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_defs.cxx.o
.PHONY : inc/moc_defs.cxx.o

inc/moc_defs.i: inc/moc_defs.cxx.i
.PHONY : inc/moc_defs.i

# target to preprocess a source file
inc/moc_defs.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_defs.cxx.i
.PHONY : inc/moc_defs.cxx.i

inc/moc_defs.s: inc/moc_defs.cxx.s
.PHONY : inc/moc_defs.s

# target to generate assembly for a file
inc/moc_defs.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_defs.cxx.s
.PHONY : inc/moc_defs.cxx.s

inc/moc_desk.o: inc/moc_desk.cxx.o
.PHONY : inc/moc_desk.o

# target to build an object file
inc/moc_desk.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_desk.cxx.o
.PHONY : inc/moc_desk.cxx.o

inc/moc_desk.i: inc/moc_desk.cxx.i
.PHONY : inc/moc_desk.i

# target to preprocess a source file
inc/moc_desk.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_desk.cxx.i
.PHONY : inc/moc_desk.cxx.i

inc/moc_desk.s: inc/moc_desk.cxx.s
.PHONY : inc/moc_desk.s

# target to generate assembly for a file
inc/moc_desk.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_desk.cxx.s
.PHONY : inc/moc_desk.cxx.s

inc/moc_deskapp.o: inc/moc_deskapp.cxx.o
.PHONY : inc/moc_deskapp.o

# target to build an object file
inc/moc_deskapp.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskapp.cxx.o
.PHONY : inc/moc_deskapp.cxx.o

inc/moc_deskapp.i: inc/moc_deskapp.cxx.i
.PHONY : inc/moc_deskapp.i

# target to preprocess a source file
inc/moc_deskapp.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskapp.cxx.i
.PHONY : inc/moc_deskapp.cxx.i

inc/moc_deskapp.s: inc/moc_deskapp.cxx.s
.PHONY : inc/moc_deskapp.s

# target to generate assembly for a file
inc/moc_deskapp.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskapp.cxx.s
.PHONY : inc/moc_deskapp.cxx.s

inc/moc_deskdev.o: inc/moc_deskdev.cxx.o
.PHONY : inc/moc_deskdev.o

# target to build an object file
inc/moc_deskdev.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskdev.cxx.o
.PHONY : inc/moc_deskdev.cxx.o

inc/moc_deskdev.i: inc/moc_deskdev.cxx.i
.PHONY : inc/moc_deskdev.i

# target to preprocess a source file
inc/moc_deskdev.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskdev.cxx.i
.PHONY : inc/moc_deskdev.cxx.i

inc/moc_deskdev.s: inc/moc_deskdev.cxx.s
.PHONY : inc/moc_deskdev.s

# target to generate assembly for a file
inc/moc_deskdev.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskdev.cxx.s
.PHONY : inc/moc_deskdev.cxx.s

inc/moc_deskfile.o: inc/moc_deskfile.cxx.o
.PHONY : inc/moc_deskfile.o

# target to build an object file
inc/moc_deskfile.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskfile.cxx.o
.PHONY : inc/moc_deskfile.cxx.o

inc/moc_deskfile.i: inc/moc_deskfile.cxx.i
.PHONY : inc/moc_deskfile.i

# target to preprocess a source file
inc/moc_deskfile.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskfile.cxx.i
.PHONY : inc/moc_deskfile.cxx.i

inc/moc_deskfile.s: inc/moc_deskfile.cxx.s
.PHONY : inc/moc_deskfile.s

# target to generate assembly for a file
inc/moc_deskfile.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskfile.cxx.s
.PHONY : inc/moc_deskfile.cxx.s

inc/moc_deskfolder.o: inc/moc_deskfolder.cxx.o
.PHONY : inc/moc_deskfolder.o

# target to build an object file
inc/moc_deskfolder.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskfolder.cxx.o
.PHONY : inc/moc_deskfolder.cxx.o

inc/moc_deskfolder.i: inc/moc_deskfolder.cxx.i
.PHONY : inc/moc_deskfolder.i

# target to preprocess a source file
inc/moc_deskfolder.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskfolder.cxx.i
.PHONY : inc/moc_deskfolder.cxx.i

inc/moc_deskfolder.s: inc/moc_deskfolder.cxx.s
.PHONY : inc/moc_deskfolder.s

# target to generate assembly for a file
inc/moc_deskfolder.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskfolder.cxx.s
.PHONY : inc/moc_deskfolder.cxx.s

inc/moc_deskicon.o: inc/moc_deskicon.cxx.o
.PHONY : inc/moc_deskicon.o

# target to build an object file
inc/moc_deskicon.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskicon.cxx.o
.PHONY : inc/moc_deskicon.cxx.o

inc/moc_deskicon.i: inc/moc_deskicon.cxx.i
.PHONY : inc/moc_deskicon.i

# target to preprocess a source file
inc/moc_deskicon.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskicon.cxx.i
.PHONY : inc/moc_deskicon.cxx.i

inc/moc_deskicon.s: inc/moc_deskicon.cxx.s
.PHONY : inc/moc_deskicon.s

# target to generate assembly for a file
inc/moc_deskicon.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_deskicon.cxx.s
.PHONY : inc/moc_deskicon.cxx.s

inc/moc_dockapp.o: inc/moc_dockapp.cxx.o
.PHONY : inc/moc_dockapp.o

# target to build an object file
inc/moc_dockapp.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockapp.cxx.o
.PHONY : inc/moc_dockapp.cxx.o

inc/moc_dockapp.i: inc/moc_dockapp.cxx.i
.PHONY : inc/moc_dockapp.i

# target to preprocess a source file
inc/moc_dockapp.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockapp.cxx.i
.PHONY : inc/moc_dockapp.cxx.i

inc/moc_dockapp.s: inc/moc_dockapp.cxx.s
.PHONY : inc/moc_dockapp.s

# target to generate assembly for a file
inc/moc_dockapp.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockapp.cxx.s
.PHONY : inc/moc_dockapp.cxx.s

inc/moc_dockbar.o: inc/moc_dockbar.cxx.o
.PHONY : inc/moc_dockbar.o

# target to build an object file
inc/moc_dockbar.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockbar.cxx.o
.PHONY : inc/moc_dockbar.cxx.o

inc/moc_dockbar.i: inc/moc_dockbar.cxx.i
.PHONY : inc/moc_dockbar.i

# target to preprocess a source file
inc/moc_dockbar.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockbar.cxx.i
.PHONY : inc/moc_dockbar.cxx.i

inc/moc_dockbar.s: inc/moc_dockbar.cxx.s
.PHONY : inc/moc_dockbar.s

# target to generate assembly for a file
inc/moc_dockbar.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockbar.cxx.s
.PHONY : inc/moc_dockbar.cxx.s

inc/moc_dockbartop.o: inc/moc_dockbartop.cxx.o
.PHONY : inc/moc_dockbartop.o

# target to build an object file
inc/moc_dockbartop.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockbartop.cxx.o
.PHONY : inc/moc_dockbartop.cxx.o

inc/moc_dockbartop.i: inc/moc_dockbartop.cxx.i
.PHONY : inc/moc_dockbartop.i

# target to preprocess a source file
inc/moc_dockbartop.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockbartop.cxx.i
.PHONY : inc/moc_dockbartop.cxx.i

inc/moc_dockbartop.s: inc/moc_dockbartop.cxx.s
.PHONY : inc/moc_dockbartop.s

# target to generate assembly for a file
inc/moc_dockbartop.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockbartop.cxx.s
.PHONY : inc/moc_dockbartop.cxx.s

inc/moc_dockicon.o: inc/moc_dockicon.cxx.o
.PHONY : inc/moc_dockicon.o

# target to build an object file
inc/moc_dockicon.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockicon.cxx.o
.PHONY : inc/moc_dockicon.cxx.o

inc/moc_dockicon.i: inc/moc_dockicon.cxx.i
.PHONY : inc/moc_dockicon.i

# target to preprocess a source file
inc/moc_dockicon.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockicon.cxx.i
.PHONY : inc/moc_dockicon.cxx.i

inc/moc_dockicon.s: inc/moc_dockicon.cxx.s
.PHONY : inc/moc_dockicon.s

# target to generate assembly for a file
inc/moc_dockicon.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockicon.cxx.s
.PHONY : inc/moc_dockicon.cxx.s

inc/moc_dockmenu.o: inc/moc_dockmenu.cxx.o
.PHONY : inc/moc_dockmenu.o

# target to build an object file
inc/moc_dockmenu.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockmenu.cxx.o
.PHONY : inc/moc_dockmenu.cxx.o

inc/moc_dockmenu.i: inc/moc_dockmenu.cxx.i
.PHONY : inc/moc_dockmenu.i

# target to preprocess a source file
inc/moc_dockmenu.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockmenu.cxx.i
.PHONY : inc/moc_dockmenu.cxx.i

inc/moc_dockmenu.s: inc/moc_dockmenu.cxx.s
.PHONY : inc/moc_dockmenu.s

# target to generate assembly for a file
inc/moc_dockmenu.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_dockmenu.cxx.s
.PHONY : inc/moc_dockmenu.cxx.s

inc/moc_filedialog.o: inc/moc_filedialog.cxx.o
.PHONY : inc/moc_filedialog.o

# target to build an object file
inc/moc_filedialog.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_filedialog.cxx.o
.PHONY : inc/moc_filedialog.cxx.o

inc/moc_filedialog.i: inc/moc_filedialog.cxx.i
.PHONY : inc/moc_filedialog.i

# target to preprocess a source file
inc/moc_filedialog.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_filedialog.cxx.i
.PHONY : inc/moc_filedialog.cxx.i

inc/moc_filedialog.s: inc/moc_filedialog.cxx.s
.PHONY : inc/moc_filedialog.s

# target to generate assembly for a file
inc/moc_filedialog.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_filedialog.cxx.s
.PHONY : inc/moc_filedialog.cxx.s

inc/moc_frame.o: inc/moc_frame.cxx.o
.PHONY : inc/moc_frame.o

# target to build an object file
inc/moc_frame.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_frame.cxx.o
.PHONY : inc/moc_frame.cxx.o

inc/moc_frame.i: inc/moc_frame.cxx.i
.PHONY : inc/moc_frame.i

# target to preprocess a source file
inc/moc_frame.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_frame.cxx.i
.PHONY : inc/moc_frame.cxx.i

inc/moc_frame.s: inc/moc_frame.cxx.s
.PHONY : inc/moc_frame.s

# target to generate assembly for a file
inc/moc_frame.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_frame.cxx.s
.PHONY : inc/moc_frame.cxx.s

inc/moc_header.o: inc/moc_header.cxx.o
.PHONY : inc/moc_header.o

# target to build an object file
inc/moc_header.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_header.cxx.o
.PHONY : inc/moc_header.cxx.o

inc/moc_header.i: inc/moc_header.cxx.i
.PHONY : inc/moc_header.i

# target to preprocess a source file
inc/moc_header.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_header.cxx.i
.PHONY : inc/moc_header.cxx.i

inc/moc_header.s: inc/moc_header.cxx.s
.PHONY : inc/moc_header.s

# target to generate assembly for a file
inc/moc_header.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_header.cxx.s
.PHONY : inc/moc_header.cxx.s

inc/moc_images.o: inc/moc_images.cxx.o
.PHONY : inc/moc_images.o

# target to build an object file
inc/moc_images.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_images.cxx.o
.PHONY : inc/moc_images.cxx.o

inc/moc_images.i: inc/moc_images.cxx.i
.PHONY : inc/moc_images.i

# target to preprocess a source file
inc/moc_images.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_images.cxx.i
.PHONY : inc/moc_images.cxx.i

inc/moc_images.s: inc/moc_images.cxx.s
.PHONY : inc/moc_images.s

# target to generate assembly for a file
inc/moc_images.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_images.cxx.s
.PHONY : inc/moc_images.cxx.s

inc/moc_launcher.o: inc/moc_launcher.cxx.o
.PHONY : inc/moc_launcher.o

# target to build an object file
inc/moc_launcher.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_launcher.cxx.o
.PHONY : inc/moc_launcher.cxx.o

inc/moc_launcher.i: inc/moc_launcher.cxx.i
.PHONY : inc/moc_launcher.i

# target to preprocess a source file
inc/moc_launcher.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_launcher.cxx.i
.PHONY : inc/moc_launcher.cxx.i

inc/moc_launcher.s: inc/moc_launcher.cxx.s
.PHONY : inc/moc_launcher.s

# target to generate assembly for a file
inc/moc_launcher.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_launcher.cxx.s
.PHONY : inc/moc_launcher.cxx.s

inc/moc_manager.o: inc/moc_manager.cxx.o
.PHONY : inc/moc_manager.o

# target to build an object file
inc/moc_manager.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_manager.cxx.o
.PHONY : inc/moc_manager.cxx.o

inc/moc_manager.i: inc/moc_manager.cxx.i
.PHONY : inc/moc_manager.i

# target to preprocess a source file
inc/moc_manager.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_manager.cxx.i
.PHONY : inc/moc_manager.cxx.i

inc/moc_manager.s: inc/moc_manager.cxx.s
.PHONY : inc/moc_manager.s

# target to generate assembly for a file
inc/moc_manager.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_manager.cxx.s
.PHONY : inc/moc_manager.cxx.s

inc/moc_msgbox.o: inc/moc_msgbox.cxx.o
.PHONY : inc/moc_msgbox.o

# target to build an object file
inc/moc_msgbox.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_msgbox.cxx.o
.PHONY : inc/moc_msgbox.cxx.o

inc/moc_msgbox.i: inc/moc_msgbox.cxx.i
.PHONY : inc/moc_msgbox.i

# target to preprocess a source file
inc/moc_msgbox.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_msgbox.cxx.i
.PHONY : inc/moc_msgbox.cxx.i

inc/moc_msgbox.s: inc/moc_msgbox.cxx.s
.PHONY : inc/moc_msgbox.s

# target to generate assembly for a file
inc/moc_msgbox.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_msgbox.cxx.s
.PHONY : inc/moc_msgbox.cxx.s

inc/moc_paths.o: inc/moc_paths.cxx.o
.PHONY : inc/moc_paths.o

# target to build an object file
inc/moc_paths.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_paths.cxx.o
.PHONY : inc/moc_paths.cxx.o

inc/moc_paths.i: inc/moc_paths.cxx.i
.PHONY : inc/moc_paths.i

# target to preprocess a source file
inc/moc_paths.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_paths.cxx.i
.PHONY : inc/moc_paths.cxx.i

inc/moc_paths.s: inc/moc_paths.cxx.s
.PHONY : inc/moc_paths.s

# target to generate assembly for a file
inc/moc_paths.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_paths.cxx.s
.PHONY : inc/moc_paths.cxx.s

inc/moc_popup.o: inc/moc_popup.cxx.o
.PHONY : inc/moc_popup.o

# target to build an object file
inc/moc_popup.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_popup.cxx.o
.PHONY : inc/moc_popup.cxx.o

inc/moc_popup.i: inc/moc_popup.cxx.i
.PHONY : inc/moc_popup.i

# target to preprocess a source file
inc/moc_popup.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_popup.cxx.i
.PHONY : inc/moc_popup.cxx.i

inc/moc_popup.s: inc/moc_popup.cxx.s
.PHONY : inc/moc_popup.s

# target to generate assembly for a file
inc/moc_popup.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_popup.cxx.s
.PHONY : inc/moc_popup.cxx.s

inc/moc_runner.o: inc/moc_runner.cxx.o
.PHONY : inc/moc_runner.o

# target to build an object file
inc/moc_runner.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_runner.cxx.o
.PHONY : inc/moc_runner.cxx.o

inc/moc_runner.i: inc/moc_runner.cxx.i
.PHONY : inc/moc_runner.i

# target to preprocess a source file
inc/moc_runner.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_runner.cxx.i
.PHONY : inc/moc_runner.cxx.i

inc/moc_runner.s: inc/moc_runner.cxx.s
.PHONY : inc/moc_runner.s

# target to generate assembly for a file
inc/moc_runner.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_runner.cxx.s
.PHONY : inc/moc_runner.cxx.s

inc/moc_rwm.o: inc/moc_rwm.cxx.o
.PHONY : inc/moc_rwm.o

# target to build an object file
inc/moc_rwm.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_rwm.cxx.o
.PHONY : inc/moc_rwm.cxx.o

inc/moc_rwm.i: inc/moc_rwm.cxx.i
.PHONY : inc/moc_rwm.i

# target to preprocess a source file
inc/moc_rwm.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_rwm.cxx.i
.PHONY : inc/moc_rwm.cxx.i

inc/moc_rwm.s: inc/moc_rwm.cxx.s
.PHONY : inc/moc_rwm.s

# target to generate assembly for a file
inc/moc_rwm.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_rwm.cxx.s
.PHONY : inc/moc_rwm.cxx.s

inc/moc_settings.o: inc/moc_settings.cxx.o
.PHONY : inc/moc_settings.o

# target to build an object file
inc/moc_settings.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_settings.cxx.o
.PHONY : inc/moc_settings.cxx.o

inc/moc_settings.i: inc/moc_settings.cxx.i
.PHONY : inc/moc_settings.i

# target to preprocess a source file
inc/moc_settings.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_settings.cxx.i
.PHONY : inc/moc_settings.cxx.i

inc/moc_settings.s: inc/moc_settings.cxx.s
.PHONY : inc/moc_settings.s

# target to generate assembly for a file
inc/moc_settings.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_settings.cxx.s
.PHONY : inc/moc_settings.cxx.s

inc/moc_sysicon.o: inc/moc_sysicon.cxx.o
.PHONY : inc/moc_sysicon.o

# target to build an object file
inc/moc_sysicon.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_sysicon.cxx.o
.PHONY : inc/moc_sysicon.cxx.o

inc/moc_sysicon.i: inc/moc_sysicon.cxx.i
.PHONY : inc/moc_sysicon.i

# target to preprocess a source file
inc/moc_sysicon.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_sysicon.cxx.i
.PHONY : inc/moc_sysicon.cxx.i

inc/moc_sysicon.s: inc/moc_sysicon.cxx.s
.PHONY : inc/moc_sysicon.s

# target to generate assembly for a file
inc/moc_sysicon.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_sysicon.cxx.s
.PHONY : inc/moc_sysicon.cxx.s

inc/moc_systray.o: inc/moc_systray.cxx.o
.PHONY : inc/moc_systray.o

# target to build an object file
inc/moc_systray.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_systray.cxx.o
.PHONY : inc/moc_systray.cxx.o

inc/moc_systray.i: inc/moc_systray.cxx.i
.PHONY : inc/moc_systray.i

# target to preprocess a source file
inc/moc_systray.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_systray.cxx.i
.PHONY : inc/moc_systray.cxx.i

inc/moc_systray.s: inc/moc_systray.cxx.s
.PHONY : inc/moc_systray.s

# target to generate assembly for a file
inc/moc_systray.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_systray.cxx.s
.PHONY : inc/moc_systray.cxx.s

inc/moc_trash.o: inc/moc_trash.cxx.o
.PHONY : inc/moc_trash.o

# target to build an object file
inc/moc_trash.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_trash.cxx.o
.PHONY : inc/moc_trash.cxx.o

inc/moc_trash.i: inc/moc_trash.cxx.i
.PHONY : inc/moc_trash.i

# target to preprocess a source file
inc/moc_trash.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_trash.cxx.i
.PHONY : inc/moc_trash.cxx.i

inc/moc_trash.s: inc/moc_trash.cxx.s
.PHONY : inc/moc_trash.s

# target to generate assembly for a file
inc/moc_trash.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_trash.cxx.s
.PHONY : inc/moc_trash.cxx.s

inc/moc_trashdialog.o: inc/moc_trashdialog.cxx.o
.PHONY : inc/moc_trashdialog.o

# target to build an object file
inc/moc_trashdialog.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_trashdialog.cxx.o
.PHONY : inc/moc_trashdialog.cxx.o

inc/moc_trashdialog.i: inc/moc_trashdialog.cxx.i
.PHONY : inc/moc_trashdialog.i

# target to preprocess a source file
inc/moc_trashdialog.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_trashdialog.cxx.i
.PHONY : inc/moc_trashdialog.cxx.i

inc/moc_trashdialog.s: inc/moc_trashdialog.cxx.s
.PHONY : inc/moc_trashdialog.s

# target to generate assembly for a file
inc/moc_trashdialog.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_trashdialog.cxx.s
.PHONY : inc/moc_trashdialog.cxx.s

inc/moc_utils.o: inc/moc_utils.cxx.o
.PHONY : inc/moc_utils.o

# target to build an object file
inc/moc_utils.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_utils.cxx.o
.PHONY : inc/moc_utils.cxx.o

inc/moc_utils.i: inc/moc_utils.cxx.i
.PHONY : inc/moc_utils.i

# target to preprocess a source file
inc/moc_utils.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_utils.cxx.i
.PHONY : inc/moc_utils.cxx.i

inc/moc_utils.s: inc/moc_utils.cxx.s
.PHONY : inc/moc_utils.s

# target to generate assembly for a file
inc/moc_utils.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_utils.cxx.s
.PHONY : inc/moc_utils.cxx.s

inc/moc_xmlparser.o: inc/moc_xmlparser.cxx.o
.PHONY : inc/moc_xmlparser.o

# target to build an object file
inc/moc_xmlparser.cxx.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_xmlparser.cxx.o
.PHONY : inc/moc_xmlparser.cxx.o

inc/moc_xmlparser.i: inc/moc_xmlparser.cxx.i
.PHONY : inc/moc_xmlparser.i

# target to preprocess a source file
inc/moc_xmlparser.cxx.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_xmlparser.cxx.i
.PHONY : inc/moc_xmlparser.cxx.i

inc/moc_xmlparser.s: inc/moc_xmlparser.cxx.s
.PHONY : inc/moc_xmlparser.s

# target to generate assembly for a file
inc/moc_xmlparser.cxx.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/inc/moc_xmlparser.cxx.s
.PHONY : inc/moc_xmlparser.cxx.s

src/about.o: src/about.cpp.o
.PHONY : src/about.o

# target to build an object file
src/about.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/about.cpp.o
.PHONY : src/about.cpp.o

src/about.i: src/about.cpp.i
.PHONY : src/about.i

# target to preprocess a source file
src/about.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/about.cpp.i
.PHONY : src/about.cpp.i

src/about.s: src/about.cpp.s
.PHONY : src/about.s

# target to generate assembly for a file
src/about.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/about.cpp.s
.PHONY : src/about.cpp.s

src/border.o: src/border.cpp.o
.PHONY : src/border.o

# target to build an object file
src/border.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/border.cpp.o
.PHONY : src/border.cpp.o

src/border.i: src/border.cpp.i
.PHONY : src/border.i

# target to preprocess a source file
src/border.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/border.cpp.i
.PHONY : src/border.cpp.i

src/border.s: src/border.cpp.s
.PHONY : src/border.s

# target to generate assembly for a file
src/border.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/border.cpp.s
.PHONY : src/border.cpp.s

src/colordialog.o: src/colordialog.cpp.o
.PHONY : src/colordialog.o

# target to build an object file
src/colordialog.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/colordialog.cpp.o
.PHONY : src/colordialog.cpp.o

src/colordialog.i: src/colordialog.cpp.i
.PHONY : src/colordialog.i

# target to preprocess a source file
src/colordialog.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/colordialog.cpp.i
.PHONY : src/colordialog.cpp.i

src/colordialog.s: src/colordialog.cpp.s
.PHONY : src/colordialog.s

# target to generate assembly for a file
src/colordialog.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/colordialog.cpp.s
.PHONY : src/colordialog.cpp.s

src/colorsel.o: src/colorsel.cpp.o
.PHONY : src/colorsel.o

# target to build an object file
src/colorsel.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/colorsel.cpp.o
.PHONY : src/colorsel.cpp.o

src/colorsel.i: src/colorsel.cpp.i
.PHONY : src/colorsel.i

# target to preprocess a source file
src/colorsel.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/colorsel.cpp.i
.PHONY : src/colorsel.cpp.i

src/colorsel.s: src/colorsel.cpp.s
.PHONY : src/colorsel.s

# target to generate assembly for a file
src/colorsel.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/colorsel.cpp.s
.PHONY : src/colorsel.cpp.s

src/dateclock.o: src/dateclock.cpp.o
.PHONY : src/dateclock.o

# target to build an object file
src/dateclock.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dateclock.cpp.o
.PHONY : src/dateclock.cpp.o

src/dateclock.i: src/dateclock.cpp.i
.PHONY : src/dateclock.i

# target to preprocess a source file
src/dateclock.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dateclock.cpp.i
.PHONY : src/dateclock.cpp.i

src/dateclock.s: src/dateclock.cpp.s
.PHONY : src/dateclock.s

# target to generate assembly for a file
src/dateclock.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dateclock.cpp.s
.PHONY : src/dateclock.cpp.s

src/desk.o: src/desk.cpp.o
.PHONY : src/desk.o

# target to build an object file
src/desk.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/desk.cpp.o
.PHONY : src/desk.cpp.o

src/desk.i: src/desk.cpp.i
.PHONY : src/desk.i

# target to preprocess a source file
src/desk.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/desk.cpp.i
.PHONY : src/desk.cpp.i

src/desk.s: src/desk.cpp.s
.PHONY : src/desk.s

# target to generate assembly for a file
src/desk.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/desk.cpp.s
.PHONY : src/desk.cpp.s

src/deskapp.o: src/deskapp.cpp.o
.PHONY : src/deskapp.o

# target to build an object file
src/deskapp.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskapp.cpp.o
.PHONY : src/deskapp.cpp.o

src/deskapp.i: src/deskapp.cpp.i
.PHONY : src/deskapp.i

# target to preprocess a source file
src/deskapp.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskapp.cpp.i
.PHONY : src/deskapp.cpp.i

src/deskapp.s: src/deskapp.cpp.s
.PHONY : src/deskapp.s

# target to generate assembly for a file
src/deskapp.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskapp.cpp.s
.PHONY : src/deskapp.cpp.s

src/deskdev.o: src/deskdev.cpp.o
.PHONY : src/deskdev.o

# target to build an object file
src/deskdev.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskdev.cpp.o
.PHONY : src/deskdev.cpp.o

src/deskdev.i: src/deskdev.cpp.i
.PHONY : src/deskdev.i

# target to preprocess a source file
src/deskdev.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskdev.cpp.i
.PHONY : src/deskdev.cpp.i

src/deskdev.s: src/deskdev.cpp.s
.PHONY : src/deskdev.s

# target to generate assembly for a file
src/deskdev.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskdev.cpp.s
.PHONY : src/deskdev.cpp.s

src/deskfile.o: src/deskfile.cpp.o
.PHONY : src/deskfile.o

# target to build an object file
src/deskfile.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskfile.cpp.o
.PHONY : src/deskfile.cpp.o

src/deskfile.i: src/deskfile.cpp.i
.PHONY : src/deskfile.i

# target to preprocess a source file
src/deskfile.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskfile.cpp.i
.PHONY : src/deskfile.cpp.i

src/deskfile.s: src/deskfile.cpp.s
.PHONY : src/deskfile.s

# target to generate assembly for a file
src/deskfile.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskfile.cpp.s
.PHONY : src/deskfile.cpp.s

src/deskfolder.o: src/deskfolder.cpp.o
.PHONY : src/deskfolder.o

# target to build an object file
src/deskfolder.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskfolder.cpp.o
.PHONY : src/deskfolder.cpp.o

src/deskfolder.i: src/deskfolder.cpp.i
.PHONY : src/deskfolder.i

# target to preprocess a source file
src/deskfolder.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskfolder.cpp.i
.PHONY : src/deskfolder.cpp.i

src/deskfolder.s: src/deskfolder.cpp.s
.PHONY : src/deskfolder.s

# target to generate assembly for a file
src/deskfolder.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskfolder.cpp.s
.PHONY : src/deskfolder.cpp.s

src/deskicon.o: src/deskicon.cpp.o
.PHONY : src/deskicon.o

# target to build an object file
src/deskicon.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskicon.cpp.o
.PHONY : src/deskicon.cpp.o

src/deskicon.i: src/deskicon.cpp.i
.PHONY : src/deskicon.i

# target to preprocess a source file
src/deskicon.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskicon.cpp.i
.PHONY : src/deskicon.cpp.i

src/deskicon.s: src/deskicon.cpp.s
.PHONY : src/deskicon.s

# target to generate assembly for a file
src/deskicon.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/deskicon.cpp.s
.PHONY : src/deskicon.cpp.s

src/dockapp.o: src/dockapp.cpp.o
.PHONY : src/dockapp.o

# target to build an object file
src/dockapp.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockapp.cpp.o
.PHONY : src/dockapp.cpp.o

src/dockapp.i: src/dockapp.cpp.i
.PHONY : src/dockapp.i

# target to preprocess a source file
src/dockapp.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockapp.cpp.i
.PHONY : src/dockapp.cpp.i

src/dockapp.s: src/dockapp.cpp.s
.PHONY : src/dockapp.s

# target to generate assembly for a file
src/dockapp.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockapp.cpp.s
.PHONY : src/dockapp.cpp.s

src/dockbar.o: src/dockbar.cpp.o
.PHONY : src/dockbar.o

# target to build an object file
src/dockbar.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockbar.cpp.o
.PHONY : src/dockbar.cpp.o

src/dockbar.i: src/dockbar.cpp.i
.PHONY : src/dockbar.i

# target to preprocess a source file
src/dockbar.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockbar.cpp.i
.PHONY : src/dockbar.cpp.i

src/dockbar.s: src/dockbar.cpp.s
.PHONY : src/dockbar.s

# target to generate assembly for a file
src/dockbar.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockbar.cpp.s
.PHONY : src/dockbar.cpp.s

src/dockbartop.o: src/dockbartop.cpp.o
.PHONY : src/dockbartop.o

# target to build an object file
src/dockbartop.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockbartop.cpp.o
.PHONY : src/dockbartop.cpp.o

src/dockbartop.i: src/dockbartop.cpp.i
.PHONY : src/dockbartop.i

# target to preprocess a source file
src/dockbartop.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockbartop.cpp.i
.PHONY : src/dockbartop.cpp.i

src/dockbartop.s: src/dockbartop.cpp.s
.PHONY : src/dockbartop.s

# target to generate assembly for a file
src/dockbartop.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockbartop.cpp.s
.PHONY : src/dockbartop.cpp.s

src/dockicon.o: src/dockicon.cpp.o
.PHONY : src/dockicon.o

# target to build an object file
src/dockicon.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockicon.cpp.o
.PHONY : src/dockicon.cpp.o

src/dockicon.i: src/dockicon.cpp.i
.PHONY : src/dockicon.i

# target to preprocess a source file
src/dockicon.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockicon.cpp.i
.PHONY : src/dockicon.cpp.i

src/dockicon.s: src/dockicon.cpp.s
.PHONY : src/dockicon.s

# target to generate assembly for a file
src/dockicon.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockicon.cpp.s
.PHONY : src/dockicon.cpp.s

src/dockmenu.o: src/dockmenu.cpp.o
.PHONY : src/dockmenu.o

# target to build an object file
src/dockmenu.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockmenu.cpp.o
.PHONY : src/dockmenu.cpp.o

src/dockmenu.i: src/dockmenu.cpp.i
.PHONY : src/dockmenu.i

# target to preprocess a source file
src/dockmenu.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockmenu.cpp.i
.PHONY : src/dockmenu.cpp.i

src/dockmenu.s: src/dockmenu.cpp.s
.PHONY : src/dockmenu.s

# target to generate assembly for a file
src/dockmenu.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/dockmenu.cpp.s
.PHONY : src/dockmenu.cpp.s

src/filedialog.o: src/filedialog.cpp.o
.PHONY : src/filedialog.o

# target to build an object file
src/filedialog.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/filedialog.cpp.o
.PHONY : src/filedialog.cpp.o

src/filedialog.i: src/filedialog.cpp.i
.PHONY : src/filedialog.i

# target to preprocess a source file
src/filedialog.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/filedialog.cpp.i
.PHONY : src/filedialog.cpp.i

src/filedialog.s: src/filedialog.cpp.s
.PHONY : src/filedialog.s

# target to generate assembly for a file
src/filedialog.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/filedialog.cpp.s
.PHONY : src/filedialog.cpp.s

src/frame.o: src/frame.cpp.o
.PHONY : src/frame.o

# target to build an object file
src/frame.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/frame.cpp.o
.PHONY : src/frame.cpp.o

src/frame.i: src/frame.cpp.i
.PHONY : src/frame.i

# target to preprocess a source file
src/frame.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/frame.cpp.i
.PHONY : src/frame.cpp.i

src/frame.s: src/frame.cpp.s
.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/frame.cpp.s
.PHONY : src/frame.cpp.s

src/header.o: src/header.cpp.o
.PHONY : src/header.o

# target to build an object file
src/header.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/header.cpp.o
.PHONY : src/header.cpp.o

src/header.i: src/header.cpp.i
.PHONY : src/header.i

# target to preprocess a source file
src/header.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/header.cpp.i
.PHONY : src/header.cpp.i

src/header.s: src/header.cpp.s
.PHONY : src/header.s

# target to generate assembly for a file
src/header.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/header.cpp.s
.PHONY : src/header.cpp.s

src/images.o: src/images.cpp.o
.PHONY : src/images.o

# target to build an object file
src/images.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/images.cpp.o
.PHONY : src/images.cpp.o

src/images.i: src/images.cpp.i
.PHONY : src/images.i

# target to preprocess a source file
src/images.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/images.cpp.i
.PHONY : src/images.cpp.i

src/images.s: src/images.cpp.s
.PHONY : src/images.s

# target to generate assembly for a file
src/images.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/images.cpp.s
.PHONY : src/images.cpp.s

src/launcher.o: src/launcher.cpp.o
.PHONY : src/launcher.o

# target to build an object file
src/launcher.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/launcher.cpp.o
.PHONY : src/launcher.cpp.o

src/launcher.i: src/launcher.cpp.i
.PHONY : src/launcher.i

# target to preprocess a source file
src/launcher.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/launcher.cpp.i
.PHONY : src/launcher.cpp.i

src/launcher.s: src/launcher.cpp.s
.PHONY : src/launcher.s

# target to generate assembly for a file
src/launcher.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/launcher.cpp.s
.PHONY : src/launcher.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager.o: src/manager.cpp.o
.PHONY : src/manager.o

# target to build an object file
src/manager.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/manager.cpp.o
.PHONY : src/manager.cpp.o

src/manager.i: src/manager.cpp.i
.PHONY : src/manager.i

# target to preprocess a source file
src/manager.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/manager.cpp.i
.PHONY : src/manager.cpp.i

src/manager.s: src/manager.cpp.s
.PHONY : src/manager.s

# target to generate assembly for a file
src/manager.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/manager.cpp.s
.PHONY : src/manager.cpp.s

src/msgbox.o: src/msgbox.cpp.o
.PHONY : src/msgbox.o

# target to build an object file
src/msgbox.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/msgbox.cpp.o
.PHONY : src/msgbox.cpp.o

src/msgbox.i: src/msgbox.cpp.i
.PHONY : src/msgbox.i

# target to preprocess a source file
src/msgbox.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/msgbox.cpp.i
.PHONY : src/msgbox.cpp.i

src/msgbox.s: src/msgbox.cpp.s
.PHONY : src/msgbox.s

# target to generate assembly for a file
src/msgbox.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/msgbox.cpp.s
.PHONY : src/msgbox.cpp.s

src/paths.o: src/paths.cpp.o
.PHONY : src/paths.o

# target to build an object file
src/paths.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/paths.cpp.o
.PHONY : src/paths.cpp.o

src/paths.i: src/paths.cpp.i
.PHONY : src/paths.i

# target to preprocess a source file
src/paths.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/paths.cpp.i
.PHONY : src/paths.cpp.i

src/paths.s: src/paths.cpp.s
.PHONY : src/paths.s

# target to generate assembly for a file
src/paths.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/paths.cpp.s
.PHONY : src/paths.cpp.s

src/popup.o: src/popup.cpp.o
.PHONY : src/popup.o

# target to build an object file
src/popup.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/popup.cpp.o
.PHONY : src/popup.cpp.o

src/popup.i: src/popup.cpp.i
.PHONY : src/popup.i

# target to preprocess a source file
src/popup.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/popup.cpp.i
.PHONY : src/popup.cpp.i

src/popup.s: src/popup.cpp.s
.PHONY : src/popup.s

# target to generate assembly for a file
src/popup.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/popup.cpp.s
.PHONY : src/popup.cpp.s

src/runner.o: src/runner.cpp.o
.PHONY : src/runner.o

# target to build an object file
src/runner.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/runner.cpp.o
.PHONY : src/runner.cpp.o

src/runner.i: src/runner.cpp.i
.PHONY : src/runner.i

# target to preprocess a source file
src/runner.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/runner.cpp.i
.PHONY : src/runner.cpp.i

src/runner.s: src/runner.cpp.s
.PHONY : src/runner.s

# target to generate assembly for a file
src/runner.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/runner.cpp.s
.PHONY : src/runner.cpp.s

src/rwm.o: src/rwm.cpp.o
.PHONY : src/rwm.o

# target to build an object file
src/rwm.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/rwm.cpp.o
.PHONY : src/rwm.cpp.o

src/rwm.i: src/rwm.cpp.i
.PHONY : src/rwm.i

# target to preprocess a source file
src/rwm.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/rwm.cpp.i
.PHONY : src/rwm.cpp.i

src/rwm.s: src/rwm.cpp.s
.PHONY : src/rwm.s

# target to generate assembly for a file
src/rwm.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/rwm.cpp.s
.PHONY : src/rwm.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/sysicon.o: src/sysicon.cpp.o
.PHONY : src/sysicon.o

# target to build an object file
src/sysicon.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/sysicon.cpp.o
.PHONY : src/sysicon.cpp.o

src/sysicon.i: src/sysicon.cpp.i
.PHONY : src/sysicon.i

# target to preprocess a source file
src/sysicon.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/sysicon.cpp.i
.PHONY : src/sysicon.cpp.i

src/sysicon.s: src/sysicon.cpp.s
.PHONY : src/sysicon.s

# target to generate assembly for a file
src/sysicon.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/sysicon.cpp.s
.PHONY : src/sysicon.cpp.s

src/systray.o: src/systray.cpp.o
.PHONY : src/systray.o

# target to build an object file
src/systray.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/systray.cpp.o
.PHONY : src/systray.cpp.o

src/systray.i: src/systray.cpp.i
.PHONY : src/systray.i

# target to preprocess a source file
src/systray.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/systray.cpp.i
.PHONY : src/systray.cpp.i

src/systray.s: src/systray.cpp.s
.PHONY : src/systray.s

# target to generate assembly for a file
src/systray.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/systray.cpp.s
.PHONY : src/systray.cpp.s

src/trash.o: src/trash.cpp.o
.PHONY : src/trash.o

# target to build an object file
src/trash.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/trash.cpp.o
.PHONY : src/trash.cpp.o

src/trash.i: src/trash.cpp.i
.PHONY : src/trash.i

# target to preprocess a source file
src/trash.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/trash.cpp.i
.PHONY : src/trash.cpp.i

src/trash.s: src/trash.cpp.s
.PHONY : src/trash.s

# target to generate assembly for a file
src/trash.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/trash.cpp.s
.PHONY : src/trash.cpp.s

src/trashdialog.o: src/trashdialog.cpp.o
.PHONY : src/trashdialog.o

# target to build an object file
src/trashdialog.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/trashdialog.cpp.o
.PHONY : src/trashdialog.cpp.o

src/trashdialog.i: src/trashdialog.cpp.i
.PHONY : src/trashdialog.i

# target to preprocess a source file
src/trashdialog.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/trashdialog.cpp.i
.PHONY : src/trashdialog.cpp.i

src/trashdialog.s: src/trashdialog.cpp.s
.PHONY : src/trashdialog.s

# target to generate assembly for a file
src/trashdialog.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/trashdialog.cpp.s
.PHONY : src/trashdialog.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/xmlparser.o: src/xmlparser.cpp.o
.PHONY : src/xmlparser.o

# target to build an object file
src/xmlparser.cpp.o:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/xmlparser.cpp.o
.PHONY : src/xmlparser.cpp.o

src/xmlparser.i: src/xmlparser.cpp.i
.PHONY : src/xmlparser.i

# target to preprocess a source file
src/xmlparser.cpp.i:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/xmlparser.cpp.i
.PHONY : src/xmlparser.cpp.i

src/xmlparser.s: src/xmlparser.cpp.s
.PHONY : src/xmlparser.s

# target to generate assembly for a file
src/xmlparser.cpp.s:
	$(MAKE) -f CMakeFiles/rwm.dir/build.make CMakeFiles/rwm.dir/src/xmlparser.cpp.s
.PHONY : src/xmlparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... rwm"
	@echo "... inc/moc_about.o"
	@echo "... inc/moc_about.i"
	@echo "... inc/moc_about.s"
	@echo "... inc/moc_border.o"
	@echo "... inc/moc_border.i"
	@echo "... inc/moc_border.s"
	@echo "... inc/moc_colordialog.o"
	@echo "... inc/moc_colordialog.i"
	@echo "... inc/moc_colordialog.s"
	@echo "... inc/moc_colorsel.o"
	@echo "... inc/moc_colorsel.i"
	@echo "... inc/moc_colorsel.s"
	@echo "... inc/moc_dateclock.o"
	@echo "... inc/moc_dateclock.i"
	@echo "... inc/moc_dateclock.s"
	@echo "... inc/moc_defs.o"
	@echo "... inc/moc_defs.i"
	@echo "... inc/moc_defs.s"
	@echo "... inc/moc_desk.o"
	@echo "... inc/moc_desk.i"
	@echo "... inc/moc_desk.s"
	@echo "... inc/moc_deskapp.o"
	@echo "... inc/moc_deskapp.i"
	@echo "... inc/moc_deskapp.s"
	@echo "... inc/moc_deskdev.o"
	@echo "... inc/moc_deskdev.i"
	@echo "... inc/moc_deskdev.s"
	@echo "... inc/moc_deskfile.o"
	@echo "... inc/moc_deskfile.i"
	@echo "... inc/moc_deskfile.s"
	@echo "... inc/moc_deskfolder.o"
	@echo "... inc/moc_deskfolder.i"
	@echo "... inc/moc_deskfolder.s"
	@echo "... inc/moc_deskicon.o"
	@echo "... inc/moc_deskicon.i"
	@echo "... inc/moc_deskicon.s"
	@echo "... inc/moc_dockapp.o"
	@echo "... inc/moc_dockapp.i"
	@echo "... inc/moc_dockapp.s"
	@echo "... inc/moc_dockbar.o"
	@echo "... inc/moc_dockbar.i"
	@echo "... inc/moc_dockbar.s"
	@echo "... inc/moc_dockbartop.o"
	@echo "... inc/moc_dockbartop.i"
	@echo "... inc/moc_dockbartop.s"
	@echo "... inc/moc_dockicon.o"
	@echo "... inc/moc_dockicon.i"
	@echo "... inc/moc_dockicon.s"
	@echo "... inc/moc_dockmenu.o"
	@echo "... inc/moc_dockmenu.i"
	@echo "... inc/moc_dockmenu.s"
	@echo "... inc/moc_filedialog.o"
	@echo "... inc/moc_filedialog.i"
	@echo "... inc/moc_filedialog.s"
	@echo "... inc/moc_frame.o"
	@echo "... inc/moc_frame.i"
	@echo "... inc/moc_frame.s"
	@echo "... inc/moc_header.o"
	@echo "... inc/moc_header.i"
	@echo "... inc/moc_header.s"
	@echo "... inc/moc_images.o"
	@echo "... inc/moc_images.i"
	@echo "... inc/moc_images.s"
	@echo "... inc/moc_launcher.o"
	@echo "... inc/moc_launcher.i"
	@echo "... inc/moc_launcher.s"
	@echo "... inc/moc_manager.o"
	@echo "... inc/moc_manager.i"
	@echo "... inc/moc_manager.s"
	@echo "... inc/moc_msgbox.o"
	@echo "... inc/moc_msgbox.i"
	@echo "... inc/moc_msgbox.s"
	@echo "... inc/moc_paths.o"
	@echo "... inc/moc_paths.i"
	@echo "... inc/moc_paths.s"
	@echo "... inc/moc_popup.o"
	@echo "... inc/moc_popup.i"
	@echo "... inc/moc_popup.s"
	@echo "... inc/moc_runner.o"
	@echo "... inc/moc_runner.i"
	@echo "... inc/moc_runner.s"
	@echo "... inc/moc_rwm.o"
	@echo "... inc/moc_rwm.i"
	@echo "... inc/moc_rwm.s"
	@echo "... inc/moc_settings.o"
	@echo "... inc/moc_settings.i"
	@echo "... inc/moc_settings.s"
	@echo "... inc/moc_sysicon.o"
	@echo "... inc/moc_sysicon.i"
	@echo "... inc/moc_sysicon.s"
	@echo "... inc/moc_systray.o"
	@echo "... inc/moc_systray.i"
	@echo "... inc/moc_systray.s"
	@echo "... inc/moc_trash.o"
	@echo "... inc/moc_trash.i"
	@echo "... inc/moc_trash.s"
	@echo "... inc/moc_trashdialog.o"
	@echo "... inc/moc_trashdialog.i"
	@echo "... inc/moc_trashdialog.s"
	@echo "... inc/moc_utils.o"
	@echo "... inc/moc_utils.i"
	@echo "... inc/moc_utils.s"
	@echo "... inc/moc_xmlparser.o"
	@echo "... inc/moc_xmlparser.i"
	@echo "... inc/moc_xmlparser.s"
	@echo "... src/about.o"
	@echo "... src/about.i"
	@echo "... src/about.s"
	@echo "... src/border.o"
	@echo "... src/border.i"
	@echo "... src/border.s"
	@echo "... src/colordialog.o"
	@echo "... src/colordialog.i"
	@echo "... src/colordialog.s"
	@echo "... src/colorsel.o"
	@echo "... src/colorsel.i"
	@echo "... src/colorsel.s"
	@echo "... src/dateclock.o"
	@echo "... src/dateclock.i"
	@echo "... src/dateclock.s"
	@echo "... src/desk.o"
	@echo "... src/desk.i"
	@echo "... src/desk.s"
	@echo "... src/deskapp.o"
	@echo "... src/deskapp.i"
	@echo "... src/deskapp.s"
	@echo "... src/deskdev.o"
	@echo "... src/deskdev.i"
	@echo "... src/deskdev.s"
	@echo "... src/deskfile.o"
	@echo "... src/deskfile.i"
	@echo "... src/deskfile.s"
	@echo "... src/deskfolder.o"
	@echo "... src/deskfolder.i"
	@echo "... src/deskfolder.s"
	@echo "... src/deskicon.o"
	@echo "... src/deskicon.i"
	@echo "... src/deskicon.s"
	@echo "... src/dockapp.o"
	@echo "... src/dockapp.i"
	@echo "... src/dockapp.s"
	@echo "... src/dockbar.o"
	@echo "... src/dockbar.i"
	@echo "... src/dockbar.s"
	@echo "... src/dockbartop.o"
	@echo "... src/dockbartop.i"
	@echo "... src/dockbartop.s"
	@echo "... src/dockicon.o"
	@echo "... src/dockicon.i"
	@echo "... src/dockicon.s"
	@echo "... src/dockmenu.o"
	@echo "... src/dockmenu.i"
	@echo "... src/dockmenu.s"
	@echo "... src/filedialog.o"
	@echo "... src/filedialog.i"
	@echo "... src/filedialog.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/header.o"
	@echo "... src/header.i"
	@echo "... src/header.s"
	@echo "... src/images.o"
	@echo "... src/images.i"
	@echo "... src/images.s"
	@echo "... src/launcher.o"
	@echo "... src/launcher.i"
	@echo "... src/launcher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager.o"
	@echo "... src/manager.i"
	@echo "... src/manager.s"
	@echo "... src/msgbox.o"
	@echo "... src/msgbox.i"
	@echo "... src/msgbox.s"
	@echo "... src/paths.o"
	@echo "... src/paths.i"
	@echo "... src/paths.s"
	@echo "... src/popup.o"
	@echo "... src/popup.i"
	@echo "... src/popup.s"
	@echo "... src/runner.o"
	@echo "... src/runner.i"
	@echo "... src/runner.s"
	@echo "... src/rwm.o"
	@echo "... src/rwm.i"
	@echo "... src/rwm.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/sysicon.o"
	@echo "... src/sysicon.i"
	@echo "... src/sysicon.s"
	@echo "... src/systray.o"
	@echo "... src/systray.i"
	@echo "... src/systray.s"
	@echo "... src/trash.o"
	@echo "... src/trash.i"
	@echo "... src/trash.s"
	@echo "... src/trashdialog.o"
	@echo "... src/trashdialog.i"
	@echo "... src/trashdialog.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/xmlparser.o"
	@echo "... src/xmlparser.i"
	@echo "... src/xmlparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

