#############################################################################
# Makefile for building: rwm
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Sep 28 20:47:12 2010
# Project:  rwm.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile rwm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_FATAL_WARNINGS -DQT_DBUS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtDBus -I/usr/include -Iinc -Ibuild -I. -I/usr/include
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtDBus -L/usr/lib -lQtXml -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/rwm.cpp \
		src/frame.cpp \
		src/border.cpp \
		src/dockbar.cpp \
		src/launcher.cpp \
		src/dockicon.cpp \
		src/desk.cpp \
		src/header.cpp \
		src/systray.cpp \
		src/manager.cpp \
		src/filedialog.cpp \
		src/colordialog.cpp \
		src/colorsel.cpp \
		src/msgbox.cpp \
		src/runner.cpp \
		src/dateclock.cpp \
		src/sysicon.cpp \
		src/deskapp.cpp \
		src/utils.cpp \
		src/deskdev.cpp \
		src/deskfile.cpp \
		src/deskfolder.cpp \
		src/dockapp.cpp \
		src/trash.cpp \
		src/trashdialog.cpp \
		src/deskicon.cpp \
		src/dockmenu.cpp \
		src/settings.cpp \
		src/paths.cpp \
		src/images.cpp \
		src/about.cpp \
		src/dockbartop.cpp \
		src/xmlparser.cpp build/moc_rwm.cpp \
		build/moc_frame.cpp \
		build/moc_border.cpp \
		build/moc_dockbar.cpp \
		build/moc_launcher.cpp \
		build/moc_dockicon.cpp \
		build/moc_desk.cpp \
		build/moc_header.cpp \
		build/moc_systray.cpp \
		build/moc_manager.cpp \
		build/moc_filedialog.cpp \
		build/moc_colordialog.cpp \
		build/moc_colorsel.cpp \
		build/moc_msgbox.cpp \
		build/moc_runner.cpp \
		build/moc_dateclock.cpp \
		build/moc_sysicon.cpp \
		build/moc_deskapp.cpp \
		build/moc_utils.cpp \
		build/moc_deskdev.cpp \
		build/moc_deskfile.cpp \
		build/moc_deskfolder.cpp \
		build/moc_dockapp.cpp \
		build/moc_trash.cpp \
		build/moc_trashdialog.cpp \
		build/moc_deskicon.cpp \
		build/moc_dockmenu.cpp \
		build/moc_settings.cpp \
		build/moc_about.cpp
OBJECTS       = build/main.o \
		build/rwm.o \
		build/frame.o \
		build/border.o \
		build/dockbar.o \
		build/launcher.o \
		build/dockicon.o \
		build/desk.o \
		build/header.o \
		build/systray.o \
		build/manager.o \
		build/filedialog.o \
		build/colordialog.o \
		build/colorsel.o \
		build/msgbox.o \
		build/runner.o \
		build/dateclock.o \
		build/sysicon.o \
		build/deskapp.o \
		build/utils.o \
		build/deskdev.o \
		build/deskfile.o \
		build/deskfolder.o \
		build/dockapp.o \
		build/trash.o \
		build/trashdialog.o \
		build/deskicon.o \
		build/dockmenu.o \
		build/settings.o \
		build/paths.o \
		build/images.o \
		build/about.o \
		build/dockbartop.o \
		build/xmlparser.o \
		build/moc_rwm.o \
		build/moc_frame.o \
		build/moc_border.o \
		build/moc_dockbar.o \
		build/moc_launcher.o \
		build/moc_dockicon.o \
		build/moc_desk.o \
		build/moc_header.o \
		build/moc_systray.o \
		build/moc_manager.o \
		build/moc_filedialog.o \
		build/moc_colordialog.o \
		build/moc_colorsel.o \
		build/moc_msgbox.o \
		build/moc_runner.o \
		build/moc_dateclock.o \
		build/moc_sysicon.o \
		build/moc_deskapp.o \
		build/moc_utils.o \
		build/moc_deskdev.o \
		build/moc_deskfile.o \
		build/moc_deskfolder.o \
		build/moc_dockapp.o \
		build/moc_trash.o \
		build/moc_trashdialog.o \
		build/moc_deskicon.o \
		build/moc_dockmenu.o \
		build/moc_settings.o \
		build/moc_about.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		rwm.pro
QMAKE_TARGET  = rwm
DESTDIR       = 
TARGET        = rwm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rwm.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile rwm.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt/mkspecs/features/dbusadaptors.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile rwm.pro

dist: 
	@$(CHK_DIR_EXISTS) build/rwm1.0.0 || $(MKDIR) build/rwm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/rwm1.0.0/ && $(COPY_FILE) --parents src/defs.h src/rwm.h src/frame.h src/border.h src/dockbar.h src/launcher.h src/dockicon.h src/desk.h src/header.h src/systray.h src/manager.h src/filedialog.h src/colordialog.h src/colorsel.h src/msgbox.h src/runner.h src/dateclock.h src/sysicon.h src/deskapp.h src/utils.h src/deskdev.h src/deskfile.h src/deskfolder.h src/dockapp.h src/trash.h src/trashdialog.h src/deskicon.h src/dockmenu.h src/settings.h inc/paths.h inc/images.h inc/about.h inc/dockbartop.h inc/xmlparser.h build/rwm1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/rwm.cpp src/frame.cpp src/border.cpp src/dockbar.cpp src/launcher.cpp src/dockicon.cpp src/desk.cpp src/header.cpp src/systray.cpp src/manager.cpp src/filedialog.cpp src/colordialog.cpp src/colorsel.cpp src/msgbox.cpp src/runner.cpp src/dateclock.cpp src/sysicon.cpp src/deskapp.cpp src/utils.cpp src/deskdev.cpp src/deskfile.cpp src/deskfolder.cpp src/dockapp.cpp src/trash.cpp src/trashdialog.cpp src/deskicon.cpp src/dockmenu.cpp src/settings.cpp src/paths.cpp src/images.cpp src/about.cpp src/dockbartop.cpp src/xmlparser.cpp build/rwm1.0.0/ && $(COPY_FILE) --parents src/about.ui build/rwm1.0.0/ && $(COPY_FILE) --parents language/it_IT.ts language/cs_CZ.ts language/ru_RU.ts language/pl_PL.ts language/de_DE.ts language/es_ES.ts build/rwm1.0.0/ && (cd `dirname build/rwm1.0.0` && $(TAR) rwm1.0.0.tar rwm1.0.0 && $(COMPRESS) rwm1.0.0.tar) && $(MOVE) `dirname build/rwm1.0.0`/rwm1.0.0.tar.gz . && $(DEL_FILE) -r build/rwm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) rwm
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_rwm.cpp build/moc_frame.cpp build/moc_border.cpp build/moc_dockbar.cpp build/moc_launcher.cpp build/moc_dockicon.cpp build/moc_desk.cpp build/moc_header.cpp build/moc_systray.cpp build/moc_manager.cpp build/moc_filedialog.cpp build/moc_colordialog.cpp build/moc_colorsel.cpp build/moc_msgbox.cpp build/moc_runner.cpp build/moc_dateclock.cpp build/moc_sysicon.cpp build/moc_deskapp.cpp build/moc_utils.cpp build/moc_deskdev.cpp build/moc_deskfile.cpp build/moc_deskfolder.cpp build/moc_dockapp.cpp build/moc_trash.cpp build/moc_trashdialog.cpp build/moc_deskicon.cpp build/moc_dockmenu.cpp build/moc_settings.cpp build/moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_rwm.cpp build/moc_frame.cpp build/moc_border.cpp build/moc_dockbar.cpp build/moc_launcher.cpp build/moc_dockicon.cpp build/moc_desk.cpp build/moc_header.cpp build/moc_systray.cpp build/moc_manager.cpp build/moc_filedialog.cpp build/moc_colordialog.cpp build/moc_colorsel.cpp build/moc_msgbox.cpp build/moc_runner.cpp build/moc_dateclock.cpp build/moc_sysicon.cpp build/moc_deskapp.cpp build/moc_utils.cpp build/moc_deskdev.cpp build/moc_deskfile.cpp build/moc_deskfolder.cpp build/moc_dockapp.cpp build/moc_trash.cpp build/moc_trashdialog.cpp build/moc_deskicon.cpp build/moc_dockmenu.cpp build/moc_settings.cpp build/moc_about.cpp
build/moc_rwm.cpp: src/defs.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/rwm.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/rwm.h -o build/moc_rwm.cpp

build/moc_frame.cpp: src/defs.h \
		src/border.h \
		src/header.h \
		src/frame.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/frame.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/frame.h -o build/moc_frame.cpp

build/moc_border.cpp: src/defs.h \
		src/border.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/border.h -o build/moc_border.cpp

build/moc_dockbar.cpp: src/defs.h \
		src/launcher.h \
		src/rwm.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		src/dockbar.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		inc/dockbartop.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/dockbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/dockbar.h -o build/moc_dockbar.cpp

build/moc_launcher.cpp: src/defs.h \
		src/rwm.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		inc/dockbartop.h \
		src/launcher.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/launcher.h -o build/moc_launcher.cpp

build/moc_dockicon.cpp: src/frame.h \
		src/defs.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/dockicon.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/dockicon.h -o build/moc_dockicon.cpp

build/moc_desk.cpp: src/defs.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/desk.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/desk.h -o build/moc_desk.cpp

build/moc_header.cpp: src/defs.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/header.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/header.h -o build/moc_header.cpp

build/moc_systray.cpp: src/defs.h \
		src/sysicon.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/systray.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/systray.h -o build/moc_systray.cpp

build/moc_manager.cpp: src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/manager.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/manager.h -o build/moc_manager.cpp

build/moc_filedialog.cpp: src/defs.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/filedialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/filedialog.h -o build/moc_filedialog.cpp

build/moc_colordialog.cpp: src/defs.h \
		src/colorsel.h \
		src/colordialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/colordialog.h -o build/moc_colordialog.cpp

build/moc_colorsel.cpp: src/defs.h \
		src/colorsel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/colorsel.h -o build/moc_colorsel.cpp

build/moc_msgbox.cpp: src/defs.h \
		src/msgbox.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/msgbox.h -o build/moc_msgbox.cpp

build/moc_runner.cpp: src/defs.h \
		src/msgbox.h \
		src/runner.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/runner.h -o build/moc_runner.cpp

build/moc_dateclock.cpp: src/defs.h \
		src/dateclock.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/dateclock.h -o build/moc_dateclock.cpp

build/moc_sysicon.cpp: src/defs.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/sysicon.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/sysicon.h -o build/moc_sysicon.cpp

build/moc_deskapp.cpp: src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/deskapp.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/deskapp.h -o build/moc_deskapp.cpp

build/moc_utils.cpp: src/defs.h \
		src/utils.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/utils.h -o build/moc_utils.cpp

build/moc_deskdev.cpp: src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/deskdev.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/deskdev.h -o build/moc_deskdev.cpp

build/moc_deskfile.cpp: src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/deskfile.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/deskfile.h -o build/moc_deskfile.cpp

build/moc_deskfolder.cpp: src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/deskfolder.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/deskfolder.h -o build/moc_deskfolder.cpp

build/moc_dockapp.cpp: src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/dockapp.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/dockapp.h -o build/moc_dockapp.cpp

build/moc_trash.cpp: src/defs.h \
		src/utils.h \
		src/msgbox.h \
		src/trashdialog.h \
		src/trash.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/trash.h -o build/moc_trash.cpp

build/moc_trashdialog.cpp: src/defs.h \
		src/utils.h \
		src/msgbox.h \
		src/trashdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/trashdialog.h -o build/moc_trashdialog.cpp

build/moc_deskicon.cpp: src/frame.h \
		src/defs.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/deskicon.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/deskicon.h -o build/moc_deskicon.cpp

build/moc_dockmenu.cpp: src/defs.h \
		src/dockmenu.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/dockmenu.h -o build/moc_dockmenu.cpp

build/moc_settings.cpp: src/defs.h \
		src/settings.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/settings.h -o build/moc_settings.cpp

build/moc_about.cpp: inc/about.h
	/usr/bin/moc $(DEFINES) $(INCPATH) inc/about.h -o build/moc_about.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_about.h
ui_about.h: src/about.ui
	/usr/bin/uic src/about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/main.o: src/main.cpp src/defs.h \
		src/rwm.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		inc/dockbartop.h \
		inc/about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/rwm.o: src/rwm.cpp src/rwm.h \
		src/defs.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		inc/dockbartop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/rwm.o src/rwm.cpp

build/frame.o: src/frame.cpp src/frame.h \
		src/defs.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/frame.o src/frame.cpp

build/border.o: src/border.cpp src/border.h \
		src/defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/border.o src/border.cpp

build/dockbar.o: src/dockbar.cpp src/dockbar.h \
		src/defs.h \
		src/launcher.h \
		src/rwm.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		inc/dockbartop.h \
		src/dockicon.h \
		src/systray.h \
		src/sysicon.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dockbar.o src/dockbar.cpp

build/launcher.o: src/launcher.cpp src/launcher.h \
		src/defs.h \
		src/rwm.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		src/dockbar.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		inc/dockbartop.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/launcher.o src/launcher.cpp

build/dockicon.o: src/dockicon.cpp src/dockicon.h \
		src/frame.h \
		src/defs.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dockicon.o src/dockicon.cpp

build/desk.o: src/desk.cpp src/desk.h \
		src/defs.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/dockbar.h \
		src/launcher.h \
		src/rwm.h \
		inc/dockbartop.h \
		src/dockicon.h \
		src/systray.h \
		src/sysicon.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		inc/about.h \
		inc/xmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/desk.o src/desk.cpp

build/header.o: src/header.cpp src/header.h \
		src/defs.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/header.o src/header.cpp

build/systray.o: src/systray.cpp src/systray.h \
		src/defs.h \
		src/sysicon.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/systray.o src/systray.cpp

build/manager.o: src/manager.cpp src/manager.h \
		src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h \
		src/colordialog.h \
		src/colorsel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/manager.o src/manager.cpp

build/filedialog.o: src/filedialog.cpp src/filedialog.h \
		src/defs.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/filedialog.o src/filedialog.cpp

build/colordialog.o: src/colordialog.cpp src/colordialog.h \
		src/defs.h \
		src/colorsel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/colordialog.o src/colordialog.cpp

build/colorsel.o: src/colorsel.cpp src/colorsel.h \
		src/defs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/colorsel.o src/colorsel.cpp

build/msgbox.o: src/msgbox.cpp src/msgbox.h \
		src/defs.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/msgbox.o src/msgbox.cpp

build/runner.o: src/runner.cpp src/runner.h \
		src/defs.h \
		src/msgbox.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/runner.o src/runner.cpp

build/dateclock.o: src/dateclock.cpp src/dateclock.h \
		src/defs.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dateclock.o src/dateclock.cpp

build/sysicon.o: src/sysicon.cpp src/sysicon.h \
		src/defs.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sysicon.o src/sysicon.cpp

build/deskapp.o: src/deskapp.cpp src/deskapp.h \
		src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/deskapp.o src/deskapp.cpp

build/utils.o: src/utils.cpp src/utils.h \
		src/defs.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/utils.o src/utils.cpp

build/deskdev.o: src/deskdev.cpp src/deskdev.h \
		src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/deskdev.o src/deskdev.cpp

build/deskfile.o: src/deskfile.cpp src/deskfile.h \
		src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/deskfile.o src/deskfile.cpp

build/deskfolder.o: src/deskfolder.cpp src/deskfolder.h \
		src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/deskfolder.o src/deskfolder.cpp

build/dockapp.o: src/dockapp.cpp src/dockapp.h \
		src/defs.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/header.h \
		src/frame.h \
		src/border.h \
		src/desk.h \
		src/deskfolder.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dockapp.o src/dockapp.cpp

build/trash.o: src/trash.cpp src/trash.h \
		src/defs.h \
		src/utils.h \
		src/msgbox.h \
		src/trashdialog.h \
		inc/paths.h \
		inc/xmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/trash.o src/trash.cpp

build/trashdialog.o: src/trashdialog.cpp src/trashdialog.h \
		src/defs.h \
		src/utils.h \
		src/msgbox.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/trashdialog.o src/trashdialog.cpp

build/deskicon.o: src/deskicon.cpp src/deskicon.h \
		src/frame.h \
		src/defs.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/rwm.h \
		src/dockbar.h \
		src/launcher.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/dockbartop.h \
		src/trash.h \
		src/trashdialog.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/deskicon.o src/deskicon.cpp

build/dockmenu.o: src/dockmenu.cpp src/dockmenu.h \
		src/defs.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dockmenu.o src/dockmenu.cpp

build/settings.o: src/settings.cpp src/settings.h \
		src/defs.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/settings.o src/settings.cpp

build/paths.o: src/paths.cpp inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/paths.o src/paths.cpp

build/images.o: src/images.cpp inc/images.h \
		inc/paths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/images.o src/images.cpp

build/about.o: src/about.cpp inc/about.h \
		ui_about.h \
		inc/paths.h \
		inc/images.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/about.o src/about.cpp

build/dockbartop.o: src/dockbartop.cpp inc/dockbartop.h \
		src/defs.h \
		src/launcher.h \
		src/rwm.h \
		src/frame.h \
		src/border.h \
		src/header.h \
		src/desk.h \
		src/deskfolder.h \
		src/filedialog.h \
		src/msgbox.h \
		src/utils.h \
		src/deskfile.h \
		src/deskapp.h \
		src/deskdev.h \
		src/deskicon.h \
		src/trash.h \
		src/trashdialog.h \
		src/dockbar.h \
		src/systray.h \
		src/sysicon.h \
		src/dockicon.h \
		src/dockapp.h \
		src/dockmenu.h \
		src/dateclock.h \
		inc/paths.h \
		src/manager.h \
		src/colordialog.h \
		src/colorsel.h \
		src/settings.h \
		src/runner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dockbartop.o src/dockbartop.cpp

build/xmlparser.o: src/xmlparser.cpp inc/xmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/xmlparser.o src/xmlparser.cpp

build/moc_rwm.o: build/moc_rwm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_rwm.o build/moc_rwm.cpp

build/moc_frame.o: build/moc_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_frame.o build/moc_frame.cpp

build/moc_border.o: build/moc_border.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_border.o build/moc_border.cpp

build/moc_dockbar.o: build/moc_dockbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dockbar.o build/moc_dockbar.cpp

build/moc_launcher.o: build/moc_launcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_launcher.o build/moc_launcher.cpp

build/moc_dockicon.o: build/moc_dockicon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dockicon.o build/moc_dockicon.cpp

build/moc_desk.o: build/moc_desk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_desk.o build/moc_desk.cpp

build/moc_header.o: build/moc_header.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_header.o build/moc_header.cpp

build/moc_systray.o: build/moc_systray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_systray.o build/moc_systray.cpp

build/moc_manager.o: build/moc_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_manager.o build/moc_manager.cpp

build/moc_filedialog.o: build/moc_filedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_filedialog.o build/moc_filedialog.cpp

build/moc_colordialog.o: build/moc_colordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_colordialog.o build/moc_colordialog.cpp

build/moc_colorsel.o: build/moc_colorsel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_colorsel.o build/moc_colorsel.cpp

build/moc_msgbox.o: build/moc_msgbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_msgbox.o build/moc_msgbox.cpp

build/moc_runner.o: build/moc_runner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_runner.o build/moc_runner.cpp

build/moc_dateclock.o: build/moc_dateclock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dateclock.o build/moc_dateclock.cpp

build/moc_sysicon.o: build/moc_sysicon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_sysicon.o build/moc_sysicon.cpp

build/moc_deskapp.o: build/moc_deskapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_deskapp.o build/moc_deskapp.cpp

build/moc_utils.o: build/moc_utils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_utils.o build/moc_utils.cpp

build/moc_deskdev.o: build/moc_deskdev.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_deskdev.o build/moc_deskdev.cpp

build/moc_deskfile.o: build/moc_deskfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_deskfile.o build/moc_deskfile.cpp

build/moc_deskfolder.o: build/moc_deskfolder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_deskfolder.o build/moc_deskfolder.cpp

build/moc_dockapp.o: build/moc_dockapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dockapp.o build/moc_dockapp.cpp

build/moc_trash.o: build/moc_trash.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_trash.o build/moc_trash.cpp

build/moc_trashdialog.o: build/moc_trashdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_trashdialog.o build/moc_trashdialog.cpp

build/moc_deskicon.o: build/moc_deskicon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_deskicon.o build/moc_deskicon.cpp

build/moc_dockmenu.o: build/moc_dockmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dockmenu.o build/moc_dockmenu.cpp

build/moc_settings.o: build/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_settings.o build/moc_settings.cpp

build/moc_about.o: build/moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_about.o build/moc_about.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

